[2022-01-28 22:30:37,772] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_3 manual__2022-01-29T01:30:35.572881+00:00 [queued]>
[2022-01-28 22:30:37,788] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: trigger_rule.task_3 manual__2022-01-29T01:30:35.572881+00:00 [queued]>
[2022-01-28 22:30:37,788] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-28 22:30:37,788] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-28 22:30:37,788] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-28 22:30:37,803] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): task_3> on 2022-01-29 01:30:35.572881+00:00
[2022-01-28 22:30:37,807] {standard_task_runner.py:52} INFO - Started process 241584 to run task
[2022-01-28 22:30:37,810] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_rule', 'task_3', 'manual__2022-01-29T01:30:35.572881+00:00', '--job-id', '1051', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule.py', '--cfg-path', '/tmp/tmpr0pdvy7c', '--error-file', '/tmp/tmp0nw8k9rm']
[2022-01-28 22:30:37,811] {standard_task_runner.py:77} INFO - Job 1051: Subtask task_3
[2022-01-28 22:30:37,876] {logging_mixin.py:109} INFO - Running <TaskInstance: trigger_rule.task_3 manual__2022-01-29T01:30:35.572881+00:00 [running]> on host uiliam-Vostro-15-3515
[2022-01-28 22:30:37,954] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-01-29T01:30:35.572881+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-29T01:30:35.572881+00:00
[2022-01-28 22:30:37,956] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-28 22:30:37,957] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 0']
[2022-01-28 22:30:37,968] {subprocess.py:85} INFO - Output:
[2022-01-28 22:30:37,970] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-28 22:30:37,985] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=trigger_rule, task_id=task_3, execution_date=20220129T013035, start_date=20220129T013037, end_date=20220129T013037
[2022-01-28 22:30:38,022] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-28 22:30:38,063] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
